modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/qyl27/Improvisations/issues"
license = "ARR"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Improvisations"
authors = "qyl27"
displayURL = "https://github.com/qyl27/Improvisations"
description = '''
Solve the problems in Minecraft with a Mod.
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "${neoforge_architectury_version_range}"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "improvisations.mixins.json"

[[mixins]]
config = "improvisations-neoforge.mixins.json"
